### ISSUE TITLE
bitbake emqx failed

### ISSUE THREAD

**Issue by luhuadong** [meta-erlang/meta-erlang#118]
I have clone zeus branch for my yocto project (imx-5.4.47-2.2.0)

```
git clone https://github.com/joaohf/meta-erlang -b zeus
```

But when I run `bitbake emqx` to build EMQX package, I got an error : 

```
ERROR: Task (virtual:native:/home/rudy/workspace/imx8m/imx-yocto-bsp/sources/meta-erlang/recipes-devtools/rebar3/rebar3_3.13.0.bb:do_compile) failed with exit code '1'
```

How should I fix it ?
Thanks

**Comment by joaohf** [comment]
Hi @luhuadong 

Sorry my delay. I'll take a look.

**Comment by joaohf** [comment]
Unfortunately I have to drop emqx from meta-erlang due to the high complexity of making cross-compile working.

Thanks.
