### ISSUE TITLE
"Error in parse transform 'lager_transform'" in Dunfell

### ISSUE THREAD

**Issue by asuhler** [meta-erlang/meta-erlang#123]
Hey all! I'm having an issue with compiling `rabbitmq-server` in the current release of `poky/dunfell`. I continually get the following error during bitbake compilation:  
![image](https://user-images.githubusercontent.com/8608445/136094531-d759cb02-0d77-4ff6-bdc3-b7123baf30c6.png)  
  
I had this issue with my main build process, so I did the following process to isolate out the issue:  

1. Clone the poky repo from the [yocto project organization](http://git.yoctoproject.org/cgit/cgit.cgi/poky/?h=dunfell) and branch to Dunfell:  
```
git clone git://git.yoctoproject.org/poky  
cd poky
git checkout dunfell
```
  
2. In a different folder, clone `meta-erlang` and checkout `dunfell`:
```
git clone https://github.com/joaohf/meta-erlang  
cd meta-erlang  
git checkout dunfell
```
3. Copy `meta-erlang` into the `poky` root directory:
```
cp -r meta-erlang poky
```  
4. Navigate into poky and setup the build environment:  
```  
# These are the requirements for my full environment, many of these are not needed for base poky
sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev  
cd poky  
source oe-init-build-env  
```
5. Navigate into the conf directory and modify `bblayers.conf` and `local.conf`:  
```
cd conf/  
```  
#### `bblayers.conf`:  
```
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../..')}"

BBLAYERS ?= " \
  ${BSPDIR}/meta \
  ${BSPDIR}/meta-poky \
  ${BSPDIR}/meta-yocto-bsp \
  ${BSPDIR}/meta-erlang \
  "
```  
#### `local.conf` (append these values to the default dunfell file):  
```
PARALLEL_MAKE = "-j 1"  
CORE_IMAGE_EXTRA_INSTALL+="rabbitmq-server"  
```  
6. Run the bitbake for rabbitmq-server:  
```
bitbake rabbitmq-server  
```  
This results in the issue described above. I have replicated this issue on 3 different machines, all running Ubuntu 20.04.3, I will attempt again on 18.04.xx (the latest) as per the official Dunfell documentation and comment once that has been completed. What else should I try? Anything obvious I'm missing? Thanks!

**Comment by joaohf** [comment]
Hello @asuhler 

Thanks for filling up this issue.

Could you try this one: https://github.com/meta-erlang/meta-erlang/pull/124

That introduces the rabbitmq 3.8.21 which is compatible if Erlang 24.0.5

According to this page https://www.rabbitmq.com/which-erlang.html there are specific combinations between rabbitmq and erlang versions.

**Comment by asuhler** [comment]
@joaohf It compiled properly, thanks for the quick turnaround!
