### ISSUE TITLE
rabbitmq-server: Making socat dependency optional

### ISSUE THREAD

**Issue by bantu** [meta-erlang/meta-erlang#135]
### Background

232551cc2040c7c1e43f2215a257cb3e72e83381 introduced a runtime dependency on `socat` to fix #49 in case `systemd` is used.

### Problem

* `socat` depends on `readline`
* `dunfell` has `readline_8.0.bb`
* readline > 6 has `LICENSE = "GPLv3+"`

Thus, rabbitmq-server cannot be installed in combination with `systemd` if `GPLv3` is disallowed.

### Solution

Can `socat` be make optional in case `sd_notify` is available as per https://github.com/meta-erlang/meta-erlang/issues/49#issuecomment-637611728 ?

**Comment by joaohf** [comment]
Hello,

Hmm good catch. I think it's possible. I'll try some options around adding sd_notify as described in #49.

Thanks

**Comment by joaohf** [comment]
Hi,

Which rabbitmq version and YP/OE version are you using ? The 3.9.x fixed the issue in a clean way (https://github.com/rabbitmq/rabbitmq-server/commit/4992b0cc9fd8af31b5c52fedde2c389d0ff1b68f)

Would moving rabbitmq to 3.9.x work to you ?

**Comment by bantu** [comment]
@joaohf Thank you for the investigation.

> Which rabbitmq version and YP/OE version are you using ?

We are using rabbitmq-server from meta-erlang's dunfell branch (version 3.8.21) and are on Yocto 3.1.11 LTS.

> Would moving rabbitmq to 3.9.x work to you ?

Yes, that should be possible. How do you think this should be approached? Do you want to add 3.9.x to the dunfell branch?

**Comment by joaohf** [comment]
Alright, so I'm going to bring rabbitmq 3.9.x to dunfell branch. But not removing the exist ones.

**Comment by joaohf** [comment]
Hello @bantu, please checkout the #137 

I've updated rabbitmq to 3.9.8 and here is a screenshot when I ran it with systemd.

![Screenshot_2021-11-07_16-06-30](https://user-images.githubusercontent.com/278690/140662216-fa924fd1-7dbd-4d64-bf0a-43a6454f023f.png)

**Comment by bantu** [comment]
@joaohf Tested. Looks good to me. Thank you very much.
