### ISSUE TITLE
Yocto Fetch fail from downloads.apache.org/couchdb/source/3.1.1/

### ISSUE THREAD

**Issue by gookcedemir** [meta-erlang/meta-erlang#140]
I am using couchdb in my yocto image for Raspberry Pi 4. 

I am using master branch "2db0d68f5335a6152f26c27a105fa8f84eb64311" revision number in the meta-erlang repository. And my preferred version in the local.conf file has been set below:

```
PREFERRED_VERSION_erlang = "22.3"
PREFERRED_VERSION_erlang-native = "22.3"
```

I started to get the fetch fail. Because we are fetching the version from the following link: https://downloads.apache.org/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz

Unfortunately, the 3.1.1 source has been removed. Therefore, I got the fetch failure. **Could you please provide the 3.1.1 source again for the following link: https://downloads.apache.org/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz**

Below is the error I got:

```
ERROR: couchdb-3.1.1-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export PATH="build/tmp/sysroots-uninative/x86_64-linux/usr/bin:layers/poky/scripts:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot/usr/bin/crossscripts:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/sbin:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot-native/sbin:build/tmp/work/aarch64-poky-linux/couchdb/3.1.1-r0/recipe-sysroot-native/bin:layers/poky/bitbake/bin:build/tmp/hosttools"; export HOME="/var/jenkins_home"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P build/downloads 'https://downloads.apache.org/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz' --progress=dot -v failed with exit code 8, output:
--2021-12-13 11:50:05--  https://downloads.apache.org/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz
Resolving downloads.apache.org (downloads.apache.org)... 88.99.95.219, 135.181.214.104, 2a01:4f9:3a:2c57::2, ...
Connecting to downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-13 11:50:05 ERROR 404: Not Found.

ERROR: couchdb-3.1.1-r0 do_fetch: Fetcher failure for URL: 'https://downloads.apache.org/couchdb/source/3.1.1/apache-couchdb-3.1.1.tar.gz'. Unable to fetch URL from any source.
```

**Comment by joaohf** [comment]
Hello @gookcedemir thanks for the report.

So, I believe you are using dunfell branch. Could you check if this works to you: https://github.com/meta-erlang/meta-erlang/pull/141 it is a couchdb version update as the upstream couchdb has removed the 3.1.1 version from their downloads repository.

I think they did that because the version 3.1.2 fixes a security issue.

Is the version 3.1.2 a feasibly option ?

**Comment by gookcedemir** [comment]
Thank you @joaohf, 

Currently, I am using zeus and unfortunately even the recipe (meta-erlang/recipes-database/couchdb/couchdb_3.1.1.bb) has been removed. Could you please add 3.1.2 bb support to zeus as well.

Please also update the dunfell, following releases until honister (hardknott and gatesgarth) to 3.1.2 because all those are using 3.1.1. Therefore, all other branches will have fetching issue and only honister is currently supporting available source.

**Comment by joaohf** [comment]
Alright, the meta-erlang zeus branch didn't have the couchdb. Now it has:

Adding couchdb for Zeus: https://github.com/meta-erlang/meta-erlang/pull/144

I didn't validate it yet. I'm planning to do soon.

Updates for other branches:

https://github.com/meta-erlang/meta-erlang/pull/143
https://github.com/meta-erlang/meta-erlang/pull/142
https://github.com/meta-erlang/meta-erlang/pull/141

**Comment by joaohf** [comment]
Closing now, feel free to reopen if need.
