### ISSUE TITLE
Cannot build epmd recipe on honister due to autoconf 2.71

### ISSUE THREAD

**Issue by colrack** [meta-erlang/meta-erlang#149]
Seems like epmd is not buildable in honister due to autoconf, here is the relevant log.
Currently I have a workaround to fallback to use autoconf 2.69 to build this recipe.
This is not ideal but I currently cannot figure out how to port the recipe to use autoconf 2.71
Any help? Thanks!

related: 
https://github.com/asdf-vm/asdf-erlang/issues/195 
https://github.com/kerl/kerl/issues/359

```
| configure.in:3205: You should run autoupdate.
| ../autoconf-2.71/lib/autoconf/general.m4:2997: AC_TRY_RUN is expanded from...
| configure.in:3205: the top level
| configure.in:3285: warning: The macro `AC_TRY_COMPILE' is obsolete.
| configure.in:3285: You should run autoupdate.
| ../autoconf-2.71/lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
| configure.in:3285: the top level
| configure.in:3415: warning: The macro `AC_FD_CC' is obsolete.
| configure.in:3415: You should run autoupdate.
| ../autoconf-2.71/lib/autoconf/general.m4:399: AC_FD_CC is expanded from...
| aclocal.m4:2771: ERL_TRY_LINK_JAVA is expanded from...
| ../autoconf-2.71/lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
| ../autoconf-2.71/lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
| ../autoconf-2.71/lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
| ../autoconf-2.71/lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
| configure.in:3415: the top level
| perl: warning: Setting locale failed.
| perl: warning: Please check that your locale settings:
| 	LANGUAGE = (unset),
| 	LC_ALL = "en_US.UTF-8",
| 	LANG = (unset)
|     are supported and installed on your system.
| perl: warning: Falling back to the standard locale ("C").
| autoheader: warning: autoconf input should be named 'configure.ac', not 'configure.in'
| perl: warning: Setting locale failed.
| perl: warning: Please check that your locale settings:
| 	LANGUAGE = (unset),
| 	LC_ALL = "en_US.UTF-8",
| 	LANG = (unset)
|     are supported and installed on your system.
| perl: warning: Falling back to the standard locale ("C").
| configure.in: error: required file 'config.sub' not found
| configure.in: error: required file 'config.guess' not found
| configure.in: error: required file 'install-sh' not found
| configure.in:   try running autoreconf --install
| WARNING: exit code 1 from a shell command.
NOTE: recipe epmd-23.1.2-r0: task do_configure: Failed
ERROR: Task (/poky/meta-erlang/recipes-core/epmd/epmd_23.1.2.bb:do_configure) failed with exit code '1'
````

**Comment by joaohf** [comment]
Hello @colrack 

Thanks for bring this up. Could you check this PR https://github.com/meta-erlang/meta-erlang/pull/152 it adds Erlang 24.2 and fix epmd cross-compile issue.

**Comment by colrack** [comment]
Hi @joaohf 
I tried it but I still have an issue here:
https://github.com/meta-erlang/meta-erlang/blob/fa7b79338e2004ba9f88c18c3d401a93b2c71f8e/recipes-core/epmd/epmd.inc#L68
My path ends with `linux-gnu` instead of `linux`, I think this is due to autoconf 2.71 that appends `gnu`
I think it happens here:
https://github.com/erlang/otp/blob/OTP-24.2/make/target.mk#L58

**Comment by joaohf** [comment]
Hi @colrack 

Alright, I have a fix for it. I'll add it to the PR.

**Comment by joaohf** [comment]
@colrack could you give a try now ?

It should work for all archs. As the epmd recipe is not calling the Erlang/OTP make install rule, the recipe has to get the correct target triple in order to collect the epmd binary.

 (https://github.com/meta-erlang/meta-erlang/pull/152/commits/2dc314cca637355d7c92681e10bbd45477fbc484)

**Comment by colrack** [comment]
Thanks a lot @joaohf 
It works now
