### ISSUE TITLE
VerneMQ support

### ISSUE THREAD

**Issue by timoc** [meta-erlang/meta-erlang#158]
Could you add VerneMQ?
https://vernemq.com/

**Comment by joaohf** [comment]
Hello. Yes I can.

**Comment by MaartenBE** [comment]
Hi I am also interested in VerneMQ support. @joaohf Any idea if the support can be added anytime soon? Thanks!

**Comment by joaohf** [comment]
Hello!

Here is a very first results: https://github.com/meta-erlang/meta-erlang/pull/164

**Comment by tvroegop** [comment]
Hi @joaohf, I have tried your patch in our yocto environment (dunfell) and was able to build a working (as in startable) vernemq with these recipes. I'm ok with this addition. Thank you for the effort.

**Comment by joaohf** [comment]
I've added vernemq to dunfell and master:

https://github.com/meta-erlang/meta-erlang/pull/174
https://github.com/meta-erlang/meta-erlang/pull/164

**Comment by joaohf** [comment]
Feel free to reopen if needed ;)
