### ISSUE TITLE
Change CouchDB source download url

### ISSUE THREAD

**Issue by dmrayt** [meta-erlang/meta-erlang#165]
CouchDB Version 3.2.0 is not available anymore on https://downloads.apache.org/couchdb/source/.
It seems that only last version is available there.
Same problem as in #140.

The source should be downloaded directly from GitHub https://github.com/apache/couchdb with the right tag (e.g 3.2.0).

**Comment by joaohf** [comment]
I've updated master and honister to couchdb 3.2.2 release

https://github.com/meta-erlang/meta-erlang/pull/167
https://github.com/meta-erlang/meta-erlang/pull/168

Let me know if you really need the 3.2.0 or the 3.2.2 works as well.

Thanks

**Comment by dmrayt** [comment]
I'm not sure but I think I could live with 3.2.2. 
The problem is that I'm using dunfell and there is other bug there, see #166. 
At the moment i'm not able to build a version without problem.
I was happy with couchdb version 3.1.1 and I have to update only because the recipe doesn't use  the source from github.

**Comment by joaohf** [comment]
I've updated master, honister and dunfell to use Apache Foundation mirrors at http://archive.apache.org/dist/couchdb/source/ 

So, I hope the couchdb versions will be there for a long time. This is also the same approach that YP/OE does for some other apache projects.

Now, the branch X couchdb versions are:

dunfell: couchdb 3.1.x
honister: couchdb 3.2.x
master: couchdb 3.2.x
