### ISSUE TITLE
Update quickstart guide for kirkstone

### ISSUE THREAD

**Issue by chrta** [meta-erlang/meta-erlang#195]
https://meta-erlang.github.io/#/guides-quickstart still refers to the dunfell branch.
It needs a few minor changes for kirkstone, e.g. adding meta-oe because of wxwidgets:
```
bitbake-layers add-layer ../meta-openembedded/meta-oe
```
Should this update be done or should we wait with it? Are other doc pages that should be updated?

**Comment by joaohf** [comment]
Hello @chrta 

Yes, you are right. I guess the quickstart (https://github.com/meta-erlang/meta-erlang.github.io/blob/main/docs/guides-quickstart.md) is the main one that we should update. 

The others md documents should work with any version.
