### ISSUE TITLE
couch db compilation error 

### ISSUE THREAD

**Issue by phantom-j** [meta-erlang/meta-erlang#199]
Hi,
I have added meta-erlang in my yocto project,
In couchdb compilation i have encountered below error

ERROR: couchdb-3.1.2-r1 do_compile: oe_runmake failed
ERROR: couchdb-3.1.2-r1 do_compile: Execution of '/home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/temp/run.do_compile.4199' failed with exit code 1:
Package erl_ei was not found in the pkg-config search path.
Perhaps you should add the directory containing `erl_ei.pc'
to the PKG_CONFIG_PATH environment variable
No package 'erl_ei' found
Package erl_ei was not found in the pkg-config search path.
Perhaps you should add the directory containing `erl_ei.pc'
to the PKG_CONFIG_PATH environment variable
No package 'erl_ei' found
==> config (compile)
==> b64url (compile)
/home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: cannot find -lei
collect2: error: ld returned 1 exit status
ERROR: sh(aarch64-poky-linux-gcc  -mcpu=cortex-a53+crc+crypto -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/recipe-sysroot c_src/b64url.o -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now -shared  -L/home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/recipe-sysroot/usr/lib/erlang/lib/erl_interface-/lib/ -lei -o priv/b64url.so)
failed with return code 1 and the following output:
/home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: cannot find -lei
collect2: error: ld returned 1 exit status

ERROR: compile failed while processing /home/leo/Documents/imx8mm/mys-8mmx-yocto/imx-yocto-bsp/build-kiara/tmp/work/aarch64-poky-linux/couchdb/3.1.2-r1/apache-couchdb-3.1.2/src/b64url: rebar_abort
Makefile:125: recipe for target 'couch' failed
make: *** [couch] Error 1
WARNING: exit code 1 from a shell command.

**Comment by joaohf** [comment]
Hello Jay.

Thanks for reporting that. Which meta-erlang are you using ? And what is
the yocto version ?



Em qua, 17 de ago de 2022 9:01 AM, Jay ***@***.***> escreveu:

**Comment by phantom-j** [comment]
Hi,
i am using meta-erlang zeus branch,
first i added below variable in local.conf ,its working fine 
IMAGE_INSTALL_append = " erlang"
after that i added couchdb package in my image bb class file,then its giving above error posted

**Comment by joaohf** [comment]
Hello,

Please, try this one https://github.com/meta-erlang/meta-erlang/pull/210

I've tested with Erlang 22.3 as I had to backport some patches from dunfell to zeus.

BTW, Zeus branch is considered EOL. If you can, I recommend to switch to Dunfell branch or Kirkstone (https://wiki.yoctoproject.org/wiki/Releases).

Thanks.
