### ISSUE TITLE
Feature Request: Add support for rustler in mix projects

### ISSUE THREAD

**Issue by chrta** [meta-erlang/meta-erlang#200]
I would like to be able to use rustler https://github.com/rusterlium/rustler from a mix-based Elixir project when using yocto kirkstone (that includes support for rust and cargo).

We probably have to write a new mix-rustler.bbclass so mix is able to detect cargo etc.

I nobody has already done that i could give it a shot with some assistance.

**Comment by chrta** [comment]
Related to https://github.com/rusterlium/rustler/issues/274

**Comment by joaohf** [comment]
Hi @chrta 

Sure that is possible. Do you have anything in mind or already have some prototype ? Would be nice to create an example project here https://github.com/meta-erlang/hello-world and https://github.com/meta-erlang/meta-erlang/tree/master/recipes-examples

**Comment by chrta** [comment]
I do not have a prototype yet. I just played around with rustler and did not manage to build the native and Elixir part at the same time. I can create a PR in https://github.com/meta-erlang/hello-world to add a minimal Elixir example using rustler. I can also create a PR to add a (not working) recipe, in recipe-examples as a starting point.

We probably have to set some environment variables and/or provide a config for the mix compile step in rustler at https://github.com/rusterlium/rustler/blob/master/rustler_mix/lib/rustler/compiler.ex
Also we have to use the functionality from https://git.yoctoproject.org/poky/tree/meta/classes/cargo.bbclass?h=kirkstone and/or https://git.yoctoproject.org/poky/tree/meta/classes/cargo_common.bbclass?h=kirkstone

**Comment by joaohf** [comment]
Alright,
Please, open a PR for hello-world there. It will be useful even it is not working, yet.

I'll start some exploration to understand how rust and the related bbclass works. But, at least for now, inherit a mix-rustler.bbclass is good start point.

**Comment by joaohf** [comment]
Hi @chrta 

This is a first try https://github.com/meta-erlang/meta-erlang/pull/201

What do you think ? I'm still not familiar with rust env and I'm learning it now.

mix-rustler.bbclass is based on cargo.bbclass 

```
bitbake hello-elixir-rustler -c compile

file /build/tmp/work/core2-64-poky-linux/hello-elixir-rustler/0.1.0-gitAUTOINC+355feef830-r0/hello-elixir-rustler/priv/native/libhelloelixirrustler_rustlernif.so
/build/tmp/work/core2-64-poky-linux/hello-elixir-rustler/0.1.0-gitAUTOINC+355feef830-r0/hello-elixir-rustler/priv/native/libhelloelixirrustler_rustlernif.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4c040657b0638136df623b6368fc5a8812a7e097, not stripped
```

I didn't try to install it yet and check what happens. Also my MACHINE is qemux86-64, I'll try others as well.

**Comment by chrta** [comment]
Great, thank you for the fast response. The PR looks good, i will continue the discussion there.

**Comment by joaohf** [comment]
It has been implemented, https://github.com/meta-erlang/meta-erlang/pull/201
