### ISSUE TITLE
erlinit fetch is failing

### ISSUE THREAD

**Issue by phantom-j** [meta-erlang/meta-erlang#209]
Hi,
i am using erlang zeus branch.
i have added erlinit package in my image file,
it's failing in fecth only .

ERROR: erlinit-1.6.0-gitAUTOINC+53b0a4dfc5-r0 do_fetch: Fetcher failure for URL: 'git://github.com/nerves-project/erlinit;branch=master'. Unable to fetch URL from any source.

**Comment by joaohf** [comment]
Hi,

This should fix the problem https://github.com/meta-erlang/meta-erlang/commit/494b1efc8bb951cbee3ca8df5d2ceff4ce078c05

Try again with zeus branch.
