### ISSUE TITLE
[Kirstone] Error while building elixir-native-1.13.4

### ISSUE THREAD

**Issue by alexandrefresnais** [meta-erlang/meta-erlang#226]
Hello guys!

I am sorry for bothering you, I am starting my Yocto journey and am struggling to simply add `rabbitmq-server` to my image.

I am creating my own layer and doing the following:

Added to `conf/layer.conf`:
```
# meta-erlang-elixir
PREFERRED_VERSION_elixir = "1.13.4"
PREFERRED_VERSION_elixir-native = "1.13.4"
PREFERRED_VERSION_nativesdk-elixir = "1.13.4"

# meta-erlang-erlang
PREFERRED_VERSION_erlang = "24.3.4.8"
PREFERRED_VERSION_erlang-native = "24.3.4.8"
PREFERRED_VERSION_nativesdk-erlang = "24.3.4.8"
```

Added to image recipe:
```
IMAGE_INSTALL:append = " rabbitmq-server"
```

When I bitbake my image, I get the following error:
```
ERROR: elixir-native-1.13.4-r0 do_compile: oe_runmake failed
ERROR: elixir-native-1.13.4-r0 do_compile: ExecutionError('<..>/yocto/build/tmp/work/x86_64-linux/elixir-native/1.13.4-r0/temp/run.do_compile.2494411', 1, None, None)
ERROR: Logfile of failure stored in: <..>/yocto/build/tmp/work/x86_64-linux/elixir-native/1.13.4-r0/temp/log.do_compile.2494411
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8
| {"init terminating in do_boot",{undef,[{make,all_or_nothing,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
| init terminating in do_boot ({undef,[{make,all_or_nothing,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
| 
| Crash dump is being written to: erl_crash.dump...done
| make: *** [Makefile:79: erlang] Error 1
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
```

Here is my bblayers.conf:
```
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  <..>/yocto/poky/meta \
   <..>/yocto/poky/meta-poky \
   <..>/yocto/poky/meta-yocto-bsp \
   <..>/yocto/meta-openembedded/meta-oe \
   <..>/yocto/meta-raspberrypi \
   <..>/yocto/meta-erlang \
   <..>/yocto/meta-custom \
  "
```

I am working on Ubuntu 22.04.

Thank you for reading this!

**Comment by joaohf** [comment]
Hello @alexandrefresnais 

Thanks for reporting it. Let's check some points.

Could you share the file erl_crash.dump ?

Also, do you have any Erlang/OTP and/or Elixir installed on Ubuntu 22.04 ? maybe via package management or kerl ?

**Comment by alexandrefresnais** [comment]
Thanks for your quick reply!

Sorry, sharing the crash dump should have been natural. Please find `work/x86_64-linux/elixir-native/1.13.4-r0/git/lib/elixir/erl_crash.dump` attached to this message.
[dump.zip](https://github.com/meta-erlang/meta-erlang/files/10915148/dump.zip)

I have neither kerl, Erlang nor elixir on my Ubuntu 22.04.

**Comment by joaohf** [comment]
Ok, thanks.

Looks like elixir-native didn't find erlang-native. Which makes no sense.

Usually I run my tests on Ubuntu 22.04 too. But using kas-containers. I'll switch to kas and then directly to host to see if there are any inconsistency when building rabbitmq-server which also depends on elixir-native at building time.

**Comment by joaohf** [comment]
Meanwhile, did you try ?:

bitbake elixir-native -c cleansstate
bitbake erlang-native -c cleansstate
bitbake rabbitmq-server -c cleansstate

bitbake rabbitmq-server

**Comment by alexandrefresnais** [comment]
Hello,

I am very sorry for the inconvenience caused by this issue.
It appears that the commands you mentioned solved my problem.
I must have ended up in a bad state when playing with versions, and as an Yocto beginner, I am not used to cleaning the state.

Thank you very much for your kind help and again sorry for the inconvenience.

**Comment by joaohf** [comment]
Hi @alexandrefresnais 

Don't worry. That also happened to me many times when I was playing with versions.

Feel free to open more issues when needed.

Thanks.
