### ISSUE TITLE
Unable to compile CouchDB 3.2.2

### ISSUE THREAD

**Issue by dmrayt** [meta-erlang/meta-erlang#261]
While compiling CouchDB 3.2.2, I get following error:

```
beam/beam_load.c(551): Error loading function rebar:save_options/2: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 26 compiler or update your Erlang/OTP version


escript: exception error: undefined function rebar:main/1
  in function  escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
make: *** [Makefile:122: couch] Error 127
```

I'm using kirkstone branch with default erlang version 26.0.2.

I've tried with erlang versions 24.3.4.13 and 25.3.2.3 but then I've was unable to build rebar-native.

Before I was using the dunfell branch and was able to compile CouchDB 3.1.2 with erlang 20.3.8.26.

**Comment by joaohf** [comment]
Hi @dmrayt, thanks for your report.

The couchdb 3.2.x branch does not support Erlang/OTP neither 26 or 25. https://docs.couchdb.org/en/stable/whatsnew/3.2.html#version-3-2-0

So, it's best to stick with 24.x on kirkstone. I've successfully built that just to check. 

One additional point, as you already mentioned, you can set the preferred version like this:

```
PREFERRED_VERSION_erlang = "24.3.4.13"
PREFERRED_VERSION_erlang-native = "24.3.4.13"
PREFERRED_VERSION_nativesdk-erlang = "24.3.4.13"
```

Also, sometimes, when changing erlang verions using the PREFERRED_VERSION rebar3 can get wrong. So, I use to run a cleanup: **bitbake -c cleansstate rebar3-native**. Have you tried it ?

PS: I didn't try to build couchdb with Erlang/OTP 26.

Thanks.

**Comment by dmrayt** [comment]
Thanks, **bitbake -c cleansstate rebar3-native rebar-native** and Erlang/OTP 24 resolved the problem.

couchdb depends on **rebar** not on **rebar3** or i'm wrong?

**Comment by joaohf** [comment]
Hi, 

I think (not 100% sure) that newly couchdb releases use rebar3.

I'm closing this issue now. Feel free to reopen if needed.
