### ISSUE TITLE
Yocto file install error in for C binaries built using rebar3

### ISSUE THREAD

**Issue by phani35** [meta-erlang/meta-erlang#262]
rebar.config has C code compilation

{pre_hooks, [
	     {compile, "make -s -C c_src"}
	    ]}.
{post_hooks, [
	      {clean, "make -s -C c_src clean"}
	     ]}.
	     
Yocto build is failing with the below error

 do_package_qa: QA Issue: File /usr/lib64/erlang/{myinstallationfile} in package {mysourcefolder} doesn't have GNU_HASH (didn't pass LDFLAGS?)
 
 Queries ?
 Does make binary is picked up from Yocto build system or The host files system?
 Can it be controlled to build for a different target architecture?
 Is there any better way to add these C binary compilations in rebar3

**Comment by joaohf** [comment]
Hi @phani35 

So, the  binary is picked up from YP build.

You can check this example here: https://github.com/meta-erlang/hello-world/tree/master/hello-erlang-interoperability and the respective recipe here: https://github.com/meta-erlang/meta-erlang/blob/master/recipes-examples/hello-erlang-interoperability/hello-erlang-interoperability_0.1.0.bb

The trick part is the Makefile https://github.com/meta-erlang/hello-world/blob/master/hello-erlang-interoperability/c_src/Makefile

In your Makefile you have to use variables like CFLAGS, LDFLAGS from the YP environment. You can append any other flags needed.

Usually, rebar hooks calls Makefiles and this is the standard way to use it with rebar3.

Another approach is to use some other build tool like cmake or autotools to take care of C source code. But that you will ending up with two 'build tools'.

**Comment by joaohf** [comment]
Closing now.

Please, feel free to reopen if needed.
