### ISSUE TITLE
Multi-core build for erlang

### ISSUE THREAD

**Issue by bobkocisko** [meta-erlang/meta-erlang#264]
Hello!  I'm using meta-erlang to build erlang & erlang-native 26.1.2.  I have a many-core machine but it appears that only one core is being used for erlang and the build is taking forever (currently erlang is taking about 11 minutes to build; for reference, building the linux kernel via yocto takes about 1 minute).  

Are there any switches to improve the build times?

**Comment by joaohf** [comment]
Hi @bobkocisko 

Good catch. You are right. And something doesn't sound ok.

Please, check out this https://github.com/meta-erlang/meta-erlang/pull/265/commits/f61bde1fc7b362fab7ff07000280d0835514f19a

A long time ago I overwrote the PARALLEL_MAKE variable in erlang.inc. That variable disables the make -j options. As stated here https://github.com/erlang/otp/blob/master/HOWTO/INSTALL.md#building-3 the Erlang build supports it.

Now the build time results are better than before:

Before the change the build time took 590.72 seconds and enabling PARALLEL_MAKE I got 147.28 sec.

During the week I'll test the patch for dunfell and kirkstone branch if all went fine, I'm ok to merge.

Thanks.

**Comment by bobkocisko** [comment]
Thanks @joaohf!  Yes that is a huge improvement.  Build time dropped from 11m to 1m46s.  🎉
