### ISSUE TITLE
Update CouchDB to 3.3.3

### ISSUE THREAD

**Issue by CoenraadS** [meta-erlang/meta-erlang#275]
Hello

I would like to request the CouchDB recipe to update to 3.3.3

**Comment by joaohf** [comment]
Hi @CoenraadS 

Here is the update to 3.3.3:

master: https://github.com/meta-erlang/meta-erlang/pull/277
nanbield: https://github.com/meta-erlang/meta-erlang/pull/278
kirkstone: https://github.com/meta-erlang/meta-erlang/pull/276

You didn't specify a branch, then I've updated couchdb for those ones. Let me know if you need any other branch.

Thanks.

**Comment by joaohf** [comment]
Closing it now, feel free to reopen if needed.

Thanks.
