### ISSUE TITLE
rabbitmq-server compatible erlang & elixir versions in Kirkstone branch

### ISSUE THREAD

**Issue by ghuband** [meta-erlang/meta-erlang#280]
After recently updating my meta-erlang layer I started seeing connection reset problems in rabbitmq-server (version 3.10.25).  I tracked the problem down the default versions of Erlang and Elixir not compatible with the version of rabbitmq-server.  I added the following to my local.conf to fix the resets:

```
# Fix connection reset problems with rabbitmq-server
# For Erlang versions compatible with rabbitmq see
#   https://www.rabbitmq.com/which-erlang.html#eol-series
# For Elixir versions compatible with Erlang see
#   https://hexdocs.pm/elixir/compatibility-and-deprecations.html#between-elixir-and-erlang-otp
PREFERRED_VERSION_erlang = "25.3.2.8"
PREFERRED_VERSION_erlang-native = "25.3.2.8"
PREFERRED_VERSION_elixir = "1.14.3"
PREFERRED_VERSION_elixir-native = "1.14.3"
```

Suggest you mention in the README to add PREFERRED_VERSION for Erlang & Elixir for rabbitmq-server.

**Comment by joaohf** [comment]
Hi @ghuband 

Thanks for your report. You are right. I'll improve the README files in order to track the elixir X erlang X rabbitmq (and others applications) build matrix.

I'll keep this issue open until I fix it.

Thanks.

**Comment by joaohf** [comment]
Hi,

I've added preferred versions for all meta-erlang recipes per yocto release branches (master, nanbield, kirkstone)

https://meta-erlang.github.io/docs/kirkstone/applications/guides-rabbitmq/
https://meta-erlang.github.io/docs/nanbield/applications/guides-rabbitmq/
https://meta-erlang.github.io/docs/applications/guides-rabbitmq/

Thanks.
