### ISSUE TITLE
private hexpm packages not supported

### ISSUE THREAD

**Issue by christophermlewis** [meta-erlang/meta-erlang#281]
We have a private packages in hexpm it looks like meta-erlang doesn't provide a mechanic to provide the organisation key to hex so that the dependencies can be pulled.

The closest I can see is:

do_configure:prepend() {
   mix "hex.organization auth ORG --key ${HEX_TOKEN}"
}

I believe this  does not work  because of mix_do_configure in mix.bbclass forces an  install hex.local.

**Comment by joaohf** [comment]
Hi @christophermlewis 

I'll take a look into this.

**Comment by christophermlewis** [comment]
Great thanks,

I think that the 'mix deps.get' has to be moved out of mix_do_configure as any hex configuration has to happen after mix 
    mix local.hex --force.

I could be wrong...anway thanks again for looking

**Comment by christophermlewis** [comment]
@joaohf I've created a pull request 
https://github.com/meta-erlang/meta-erlang/pull/282

**Comment by joaohf** [comment]
Hi,

Closing this one now. Feel free to reopen if needed.
