### ISSUE TITLE
Fails to build without pam in DISTRO_FEATURES

### ISSUE THREAD

**Issue by rossburton** [meta-erlang/meta-erlang#339]
As discovered when running `yocto-check-layer`:
```
ERROR: Nothing PROVIDES 'libpam' (but meta-erlang/recipes-database/riak/riak_3.2.1.bb DEPENDS on or otherwise requires it)
libpam was skipped: one of 'pam systemd' needs to be in DISTRO_FEATURES
```
The riak recipe should use `features_check` and set `REQUIRED_DISTRO_FEATURES = "pam"` so that it skips itself if the distro doesn't have that enabled.

**Comment by joaohf** [comment]
Thanks @rossburton
