### ISSUE TITLE
Unable to compile CouchDB for arm64

### ISSUE THREAD

**Issue by dmrayt** [meta-erlang/meta-erlang#85]
While buiding couchdb, I get following error at compiling b64url.c:

```
| ERROR: sh(aarch64-tdx-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot c_src/b64url.o -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now -shared  -L"/yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/lib/erlang/lib/erl_interface-3.13.2/lib" -lerl_interface -lei -o priv/b64url.so)
| failed with return code 1 and the following output:
| /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin/aarch64-tdx-linux/../../libexec/aarch64-tdx-linux/gcc/aarch64-tdx-linux/9.3.0/ld: skipping incompatible /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/lib/erlang/lib/erl_interface-3.13.2/lib/liberl_interface.a when searching for -lerl_interface
| /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin/aarch64-tdx-linux/../../libexec/aarch64-tdx-linux/gcc/aarch64-tdx-linux/9.3.0/ld: cannot find -lerl_interface
| /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin/aarch64-tdx-linux/../../libexec/aarch64-tdx-linux/gcc/aarch64-tdx-linux/9.3.0/ld: skipping incompatible /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/lib/erlang/lib/erl_interface-3.13.2/lib/libei.a when searching for -lei
| /yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/bin/aarch64-tdx-linux/../../libexec/aarch64-tdx-linux/gcc/aarch64-tdx-linux/9.3.0/ld: cannot find -lei
| collect2: error: ld returned 1 exit status

```

The problem is the flag `-L"/yocto/build/tmp/work/aarch64-tdx-linux/couchdb/3.1.1-r0/recipe-sysroot-native/usr/lib/erlang/lib/erl_interface-3.13.2/lib"`, it use erlang-native (in recipe-sysroot-native) instead of the cross compiled erlang (in recipe-sysroot).

With following workaround in couchdb recipe, i was able to compile:

- add the line `LDFLAGS_append = " -L${STAGING_LIBDIR}/erlang/lib/erl_interface-3.13.2/lib"` before do_configure_append()
- replace the line `sed -i "s:-L/usr/local/lib:-L${STAGING_LIBDIR}:g" ${B}/src/couch/rebar.config.script` with
`sed -i "s:-L/usr/local/lib:\$LDFLAGS:g" ${B}/src/couch/rebar.config.script` in do_configure_append()

But with this workaround both native and cross compiled library paths are used and the version of erl_interface is hard coded in recipe. A better solution is still needed.

**Comment by joaohf** [comment]
Hello @dmrayt

Could you try this one https://github.com/meta-erlang/meta-erlang/pull/86 ?

**Comment by dmrayt** [comment]
Thanks, this is the right solution.

Please, commit it also in the dunfell branch.

I would still replace the line in do_configure_append(). With this correction I was able to remove "ldflags" from INSANE_SKIP.

**Comment by joaohf** [comment]
Merged into master and dunfell. I ended up using your approach for solve the ldflags QA issue.

Thanks!

**Comment by dmrayt** [comment]
Thanks, it's working now.
