### ISSUE TITLE
CouchDB systemd service doesn't start

### ISSUE THREAD

**Issue by dmrayt** [meta-erlang/meta-erlang#87]
After installation of couchdb, the systemd service is unable to start on my embedded system.

On first start, I had following error `couchdb[1253]: erlexec: HOME must be set`. The service can not start with root rights.
I've added the couchdb user in service file, on next start the default data folder couldn't be created: Permission denied.
After changing the owner of couchdb folder, the service was able to start but stop after about one minute. The Type=forking in service file is wrong.

I was able to build a running package with following changes:
Change the owner of couchdb folder in do_install_append (): `chown -R couchdb:couchdb ${D}/opt/couchdb`
Use following couchdb.service
```
[Unit]
Description=Apache CouchDB
After=network.target remote-fs.target

[Service]
User=couchdb
Group=couchdb

ExecStart=%bindir%/couchdb -o /dev/stdout -e /dev/stderr

Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by joaohf** [comment]
Fixed by https://github.com/meta-erlang/meta-erlang/commit/f423d292cf06d93316147ee0b7bb2ef5bf5efd64

Thanks!
