### ISSUE TITLE
Add erlang 20.3.8 for couchdb

### ISSUE THREAD

**Issue by dmrayt** [meta-erlang/meta-erlang#88]
The Apache couchdb team recommend to use erlang 20.3.8.25 for couchdb 3.1.1.
https://github.com/apache/couchdb/issues/3115#issuecomment-683849187
https://github.com/apache/couchdb/issues/3273#issuecomment-729030867

**Comment by joaohf** [comment]
Alright, I'm going to add that erlang version as well.

**Comment by joaohf** [comment]
Done.

Remember to add the following configuration (nativesdk might be optional):
```
PREFERRED_VERSION_erlang = "20.3.8.26"
PREFERRED_VERSION_erlang-native = "20.3.8.26" 
PREFERRED_VERSION_nativesdk-erlang = "20.3.8.26"
```
